consumer:
  enabled: ${CONSUMER_ENABLED:true}
server:
  port: ${APP_HTTP_PORT:8081}
spring:
  rabbitmq:
    host: mq
    port: 5672
    username: rabbitmq
    password: rabbitmq
    virtual-host: /
  cloud:
    stream:
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: mq
                port: 5672
                username: rabbitmq
                password: rabbitmq
                virtual-host: /
      instance-count: ${APP_MESSAGE_COUNT:1}
      instance-index: ${APP_MESSAGE_INDEX:0}